data = [
  {
    "id": "0",
    "x": 0,
    "y": 0,
    "imgSmall": "rx01-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Shanghai Street View in 1900s",
    "desc": "&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese Popular Culture: </b> Shanghai in the 1920s was a city filled with western modernization and often considered as the birthplace of cosmopolitanism in China. Shanghai was often known as &#34 the Oriental Paris &#34. Introduction of western modernity brought many changes in the cityscapes of Shanghai and consequently, the lifestyles of those who live in it. Since Shanghai was a treaty port of territories split and divided between the International Settlement, French Concession, and the Native Chinese sectors. Shanghai had buildings in which the appearance and function resembled those of London or New York. The city was filled with different cultures. Shanghai was a huge metropolitan city in the East filled with western infrastructures including banks, street, electricity, street lights, trams, telephone, and running water. The nightlife of night clubs and hotel rooms thrived along with many other changes in lifestyles. If it still doesn&#39t impress you, imagine the city life from the Great Gatsby in Asia.<br/> <br/> &nbsp &nbsp &nbsp &nbsp <b> Relationship with adjacent pictures: </b> With influx of western modernization and rapid changes, Shanghai became the stage of newly emerging popular cultures. From love stories in a fiction to the new music, Shanghai became the hub and center of cultural products",
    "relat":"",
    "citation":"",
    "seq": 1
  },
  {
    "id": "1",
    "x": -2,
    "y": 0,
    "imgSmall": "rx02-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Hong Kong Action Film",
    "desc": "&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese Popular Culture: </b> When people think about Chinese film, the horrible movie with Matt Damon where soldiers fight with aliens on top of the Great Wall will come to mind. However, even before the Hollywood and the Chinese film companies started working together, Chinese or more specifically, Hong Kong films were often considered as unique and innovative and influenced many countries &#39 cinema around the world. Hong Kong&#39s action film is unique in its storytelling and cinematography. Unlike its counterparts from Hollywood, the actions are much more vivid, straightforward, longer, and explicit. The films do not use much editing, jump-cuts that distract the audience from action or present pseudo-action by conveying the story and leaving the imagination to work on how each action would end up. Imagine all those great stunts by Jackie Chan but eliminate his iconic comic nature from the films and insert Martin Scorsese in the story. Many of action films from Hong Kong were remade or adapted not only in other East Asian cinema but also in Hollywood films as well. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b> Relationship with adjacent pictures: </b>Relationship with adjacent pictures: Some of the iconic figures of Hong Kong films include Bruce Lee and Chow Yun-Fat. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b> Works Cited: </b> Bordwell, David. &#34Aesthetics in Action: Kungfu, Gunplay, and Cinematic Expressivity.&#34 At Full Speed: Hong Kong Cinema in a Borderless World, by Ching-Mei Esther. Yau, University of Minnesota Press, 2003, pp. 73 &#45 93.",
    "relat":"",
    "citation":"",
    "seq": 1
  },
  { "id": "2",
    "x": 1,
    "y": 0,
    "imgSmall": "rx03-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Feng Zikai's cartoon",
    "desc": "&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese Popular Culture: </b> Feng Zikai is considered as one of the pioneers of the Chinese cartoons. Cartoon is often forgotten and comparatively considered less frequently when exploring Chinese popular culture. However, looking into Feng Zikai&#39 s cartoons and philosophy often gives insight to the history of China, religious and national perspective on the foreign invasions as well as swiftly changing politics and culture during his time. Feng Zikai&#39 s cartoon is unique that his cartoon modestly remained unchanged in its theme and association with Buddhist values during the times of Sino-Japanese war when many of the artists used their works as war propaganda. Instead of explicit demonization of the enemy or using sexual images of the Chinese victim to evoke nationalism and unity among the readers, Feng Zikai approaches war in different aspect by showing what people are fighting for, how cruel and violent it is, and that there is a glimpse of hope waiting at the end of despair. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b> Relationship with adjacent pictures:</b> Feng Zikai's buddhist philosophy draws constrast with other cartoonists at that time drawing Anti-Japanese propaganda. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b> Works Cited: </b> Chang-tai Hung, &#34 War and Peace in Feng Zikai &39 #s Wartime Cartoons, &#34 Modern China, 16:1 (January 1990), 39 &#45 83. ",
    "relat":"",
    "citation":"",
    "seq": 1
  },
  { "id": "3",
    "x": 1,
    "y": 1,
    "imgSmall": "rx04-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Anti-Japanes Propaganda",
    "desc": "&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese Popular Culture: </b> <br/> The picture of Anti-Japanese Propaganda is an example of war propaganda that existed in many different forms during Sino-Japanese war. However, it is incredibly notable of how many of those propaganda uses female sexuality and its vulnerability and victimization from Japanese army were most widely use to boost and evoke nationalism and morale along with the spirit of resistance. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b> Relationship with adjacent pictures:</b> The Anti-Japanese propaganda from the picture and others contrast  with the works of Feng Zikai, yet, both of them ultimately served same political function from similar point in time. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b> Works Cited: </b> Louis Edwards, &#34 Drawing Sexual Violence in Wartime China: Anti-Japanese Propaganda Cartoons&#34 Journal of Asian Studies, 72:3 (2013), 563 &#45 586.",
    "seq": 1
  },
  { "id": "4",
    "x": 2,
    "y": 1,
    "imgSmall": "rx05-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Mao Zedong",
    "desc": "&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese Popular Culture: </b> As a political leader and the individual who once had the greatest power over the mainland China, Mao Zedong also had great influence to the Chinese popular culture. His first explicit attempt on influencing the popular culture is visible from his talks at Yanan forum about literatures and art. In the forum, Mao is giving the guidance to the artists and his people that the art and literature should be made for the peasants, directing them as the audience and main targets. The art and literature should also be coming from the peasants encouraging to construct certain Chinese art legacy. At the end, Mao reiterates that the popular culture of China should be &#34mass culture&#34 serving its revolutionary purposes. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b> Relationship with adjacent pictures: </b> The rapid swift in different forms of popular culture being used as political propaganda like Anti-Japanese comics or even to promote communism can be all described as the consequence of Mao’s words. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b> Works Cited: </b> Mao Zedong, &#34Talks at Yan’an Forum on Literature and Art,&#34 in Modern Chinese Literary Thought: Writings on Literature, 1893-1945, ed. Kirk Denton, chapter 54. ",
    "relat":"",
    "citation":"",
    "seq": 1
  },
  { "id": "5",
    "x": -2,
    "y": -1,
    "imgSmall": "rx06-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Bruce Lee",
    "desc": "&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese Popular Culture: </b> People often consider Bruce Lee as the iconic Kung Fu action star from China. However, the influence and legacy of Bruce Lee in Chinese popular culture as well as other Asian popular culture is beyond of his successes in films. Bruce Lee was not only an actor, but an activist, a philosopher, and an idol. Bruce Lee was China. His actions, fames, and popularity brought pride and joy to not only the people of China but the people of Asia. His storytelling against foreign invasion evoked proud nationalism amongst his audience without any attachment to certain political ideology. His legacy still remains firm through the other action stars like Bruce Lee, Jet Lee, and others. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b>Relationship with adjacent pictures:</b> Bruce Lee is Hong Kong&#39s most iconic figure. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b> Works Cited:</b> &#34The Rise of Kung Fu, from Wong Fei-Hung to Bruce Lee.&#34 Chinese Martial Arts Cinema, by Stephen Teo, Edinburgh Univ. Press, 2009, pp. 58 &#45 85.",
    "relat":"",
    "citation":"",
    "seq": 1
  },
  { "id": "6",
    "x": 0,
    "y": 1,
    "imgSmall": "rx07-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Li Jinhui",
    "desc": "&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese Popular Culture: </b> Li Jinhui is the father of Chinese popular music, in modern Chinese popular music. Li Jinhui is credited for incorporating the western music of jazz and Chinese traditional folk tunes. However revolutionary, Li Jinhui&#39s new music genre was considered as pornographic, hence the title of &#34yellow music&#34 because its divergence from nationalism and focus on love stories. Yet, his work symbolizes the beginning of new popular culture in China where western modernization combines with Chinese traditions and sentiments. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b>Relationship with adjacent pictures: </b> Yellow music was born in Shanghai. With strict government censorship, Chinese Hip-Hop has become the new Yellow Music.  <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b>Works Cited:</b> &#34The Yellow Music of Li Jinhui.&#34Yellow Music: Media Culture and Colonial Modernity in the Chinese Jazz Age, by Andrew F. Jones, Duke University Press, 2006, pp. 74 &#45 104.",
    "relat":"",
    "citation":"",
    "seq": 1
  },
  {"id": "7",
    "x": -3,
    "y": 4,
    "imgSmall": "rx08-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "How to",
    "desc":"&nbsp &nbsp &nbsp &nbsp <b>Welcome to our project.</b> <br/> <br/>&nbsp &nbsp &nbsp &nbsp This image map will provide you an experience similar to visiting a museum exhibition. This image map will explore the Chinese popular culture in width not in depth. Instead of highlighting an event, figures, or other cultural forms, the map will provide the general overview of the Chinese popular culture.<br/> <br/>&nbsp &nbsp &nbsp &nbspThere is no beginning of the exhibition. The posted pictures are certainly related to the adjacent photos but the viewers can start with any of the posts. Each picture is presented with details like its significance in Chinese popular culture and the relationship with adjacent photos. However, we do not encourage the viewers to click on photos to access the detail because the user experience is maximized when users think about how and why certain pictures are juxtaposed. <br/> <br/>&nbsp &nbsp &nbsp &nbsp By the time you are done with all the photos in the website, you will have general knowledge on Chinese popular culture, different perspectives, and ability to relate seemingly unrelated events or figures as well. <br/> <br/>&nbsp &nbsp &nbsp &nbspEnjoy the map.",
    "seq":1
  },
  {"id": "8",
    "x": 0,
    "y": 2,
    "imgSmall": "rx09-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Rap of China",
    "desc":"&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese Popular Culture:</b> Rap of China is an American Idol style TV show where contestants perform hip-hop music on stage for record signing and monetary rewards. It is very significant show which transforms the youth culture of not only mainland China but in other Sinophone regions. The show introduced the underground genre of Hip-hop into the mainstream by utilizing internet as its platform rather than TV. The show influenced not only the fashion of Chinese youth but also recent trend in Chinese music, attracted foreign interest from other artists and cultures, and reiterated Chinese value by joining the traditional Chinese value and western Hip-hop culture. <br/> <br/>&nbsp &nbsp &nbsp &nbsp <b> Relationship with adjacent photos: </b> With the success of the show, Rap of China, hip-hop has been considered a genre of music in which the Chinese government wants to have control over due to music’s idiosyncratic vulgar and critical nature. Just like the Yellow music which received criticism and pressure from the authorities, Rap music in China also faced different types of government control from airing limitations and censorships. Rap of China is also a representative cultural program in recent years. It creates and leads the new trend as well as the famous and popular celebrity, Kris Wu.",
    "seq":1
  },
  {"id": "9",
    "x": 0,
    "y": 3,
    "imgSmall": "rx10-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Kris Wu",
    "desc":"&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese Popular Culture:</b> Serving as a judge and iconic figure of the popular program called Rap of China, Kris Wu is currently the most famous and popular celebrity. Started as a member of Korean pop idol, Kris Wu is not only a singer, but an actor, and a model. This Canadian Chinese celebrity’s influence is beyond imagination. From appearing in a global blockbuster directed by Luc Besson, and to perform in the halftime show of Super Bowl, Kris Wu is certainly one of the most leading figure in Chinese popular culture.<br/> <br/>&nbsp &nbsp &nbsp &nbsp<b> Relationship with adjacent photos:</b> <br/> <br/> Kris Wu is one of the judges of the Rap of China. Just like Wang Leehom, Kris Wu is also a person of foreign nationality with Chinese heritage to come back to China and build career.",
    "seq":1
  },
  {"id": "10",
    "x": 1,
    "y": 3,
    "imgSmall": "rx11-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Wang Leehom",
    "desc":"&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese Popular Culture:</b>Wang Leehom is a Chinese-American singer and songwriter. He is famous for representing the popular culture driven by those who are not native to the country of China but instead held heritage. He is famous for commenting that he did not feel belong back in the United States. Wang Leehom gained fast popularity in Taiwan by singing the song, Descendants of Dragon, in which the lyrics of the music evoke the nationalism of Taiwan. Well using his background and heritage, Wang Leehom is famous for combining Chinese materials and elements in music with western R&B. <br/> <br/>&nbsp &nbsp &nbsp &nbsp<b> Relationship with adjacent photos:</b> Kris Wu and Wang Leehom are both culture figures who have western nationalities but primarily perform and build career in Sinophone regions. Wang Leehom and Cui Jian are both musicians who greatly influence the music, Wang Leehom by incorporating American R&B, Cui Jian for bringing Rock music. ",
    "seq":1
  },
  {"id": "11",
    "x": 2,
    "y": 3,
    "imgSmall": "rx12-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Cui Jian",
    "desc":"&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese Popular Culture:</b>Cui Jian is known as the father of Chinese Rock. He is a Korean Chinese musician who was inspired by the smuggled records of rock music. His music was most popular during the times of Tiananmen Square Protests. His music, Nothing to My Name, became a protest anthem to the students of Tiananmen square. His messages and rock spirit matched with the enthusiasm and uprising of the students at that time. Cui Jian is also famous for wearing a red blindfold on his stages, a silent protest against the government censorship and control of China. <br/> <br/>&nbsp &nbsp &nbsp &nbsp<b> Relationship with adjacent photos:</b> Relationship with adjacent photos: Cui Jian, like Wang Leehom incorporated the western music and Chinese spirit and gained fame and popularity in music industry. ",
    "seq":1
  },
  {"id": "12",
    "x": 3,
    "y": 1,
    "imgSmall": "rx13-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Red Guard",
    "desc":"&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese popular culture:</b> Red Guard is a student mass paramilitary social organization and movement during the Cultural Revolution. They were the foot soldiers and frontiers of Maoism along with its swift and violent revolution. With personal support from Mao, Red Guard was a great political propaganda spreading Maoism as well as an ideology police. Red Guard had great political and physical power and exiled, discouraged, and even physically harmed many intellects and artists at that time under the label of “Four Olds” of Chinese society. The rise and actions of Red Guard should be considered as the dark ages of and lost time of Chinese popular culture. <br/> <br/>  &nbsp &nbsp &nbsp &nbsp <b>Relationships with adjacent photos:</b>Red Guard and Mao had huge influence in the construction, destruction, and distortion of Chinese popular culture by violent ideological push. ",
    "seq":1
  },
  {"id": "13",
    "x": -2,
    "y": -2,
    "imgSmall": "rx14-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Jackie Chan",
    "desc":"&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese popular culture:</b> Jackie Chan is another Chinese action movie star whose popularity may closely parallel with Bruce Lee but certainly built his own fame and legacy in a different way. He is currently one of the most well-known Chinese individual in the world. He is a martial artists, actor, director, stuntman, and singer. Unlike Bruce Lee whose masculinity and brutal actions brought his fame, Jackie Chan is famous for his distinct use of improvisation, innovative stunts, and his iconic humors in the film. As his performance and fame often resonate with the Chinese nationalism as many people consider Jackie Chan to represent China. <br/> <br/>  &nbsp &nbsp &nbsp &nbsp <b>Relationships with adjacent photos:</b> Just as Bruce Lee was symbolic figure of China through his masculinity and fascinating actions, Jackie Chan brings a different but similar meaning to the Chinese popular culture through his success in Hollywood and his distinct films. ",
    "seq":1
  },
  {"id": "14",
    "x": -3,
    "y": -2,
    "imgSmall": "rx15-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "The Great Wall",
    "desc":"&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese popular culture:</b> Ever since the growth of Chinese economy along with the ticket power of Chinese audience, many Hollywood films had incorporated different elements to enter the Chinese film market. Many films often looked for Chinese investment, incorporated China in their plots, or casted Chinese actresses and actors. The Great Wall, However, is a film directed and funded by Chinese film company with Hollywood stars as its main casts. As the most expensive film every shot in China, the Great Wall brought mixed review but nonetheless financially successful. As it is the first movie that is made from China targeted toward the world market, The Great Wallsignal a Chinese wind blowing and shifting the cinema industry. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b>Relationships with adjacent photos:</b> As Bruce Lee and Jackie Chan are iconic Chinese figures in cinema, The Great Wall exemplifies the Chinese influence in Hollywood films through its story, production, and success.",
    "seq":1
  },
  {"id": "15",
    "x": -1,
    "y": 0,
    "imgSmall": "rx16-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Eileen Chang",
    "desc":"&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese popular culture:</b>Eileen Chang is known as one of the most influential modern Chinse writers as well as the most iconic Chinese writer. She portrayed the life of Chinese people during a chaotic time period in the 1940s when foreign invasions and wars were prominent. Rather than focusing on nationalism or publishing political writings, Eileen Chang focused on writing about the everyday life highlighting love transcending and overcoming the difficulties of the time period. Some of her fictions like Lust, Caution often reflects her own stories. Many of her stories had been adopted into films and translated into different languages. Her works are recognized worldwide. <br/> <br/> &nbsp &nbsp &nbsp &nbsp <b>Relationships with adjacent photos:</b> Many of Eileen Chang’s stories were placed in Shanghai. When her written works were adopted into films, they were often premiered and produced in Hong Kong cinema for her works were often censored and forbidden by the Chinese government due to its sexual and controversial content related to Japanese occupation of China. ",
    "seq":1
  },
  {"id": "16",
    "x": -3,
    "y": 0,
    "imgSmall": "rx17-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Umbrella Movement",
    "desc":"&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese popular culture:</b>Umbrella movement is another name of a political movement during the Hong Kong democracy protests. The movement sparked by the controversial pre-screening of candidates for the election of Hong Kong. The movement was named as Umbrella movement when the protesters mainly composed of students defended themselves from tear gas by using umbrellas. It represented a huge moment of Youth culture in China where student rose against the decisions of government to voice out their opinions. The movement is also deeply related to Chinese popular culture for students utilized different internet and technology culture to voice out and reach out to another.<br/> <br/>&nbsp &nbsp &nbsp &nbsp<b> Relationship with adjacent photos:</b> The famous Umbrella movement took place in Hong Kong.",
    "seq":1
  },
  {"id": "17",
    "x": -4,
    "y": 0,
    "imgSmall": "rx18-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "title": "Sunflower Movement",
    "desc":"&nbsp &nbsp &nbsp &nbsp <b>Significance in Chinese popular culture:</b> Sunflower Student Movement was a protest against the decisions of ruling party of Taiwan to pass the Cross-Strait Service Trade Agreements. The students and civic groups marched and occupied the legislative chamber claiming that the signed trade pact will hurt Taiwan’s economy and its political sovereignty from mainland China. The movement later led to the change of ruling party in Taiwan. The movement, as it was led by group of students, used many popular cultures as their political tool to voice their opinions. For instance, there was English Reddit forum explaining and advertising what the movement was about and asked for support from around the world. Students held cameras to film and created documentary as well as there were many people supporting the movement through creation of posters, sharing images online, and even making cartoon versions of protest leaders.<br/> <br/>&nbsp &nbsp &nbsp &nbsp<b> Relationship with adjacent photos:</b> Similar to Umbrella movement, Sunflower Student movement is also a student and young generation led movement against the government legislature utilizing popular internet and technology culture to promote and voice their opinions. ",
    "seq":1
  },


]
